color: true
dry-run: null
hookfiles: dredd_hooks.js
language: nodejs
require: null
server: npm start
server-wait: 4
init: false
custom: {}
names: false
only: []
reporter: [html]
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 7000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 500
hooks-worker-term-timeout: 7000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: api2.md
endpoint: "http://192.168.0.100:3333"
